config/routes.rb
PlugNPlay::Application.routes.draw do
  namespace :api do
    api version: 1, module: "v1" do
      post "event/read"   , to: "event#read"
      post "event/trigger", to: "event#trigger"
    end
  end

  resource :setup, only: [:new, :create, :show]

  root "setups#show"

end

app/models/app_config.rb
class AppConfig < ActiveRecord::Base
  validates :key,
            uniqueness: true

  validates :key, :value,
            presence: true

  after_commit :flush_cache

  def self.get_value(key)
    Rails.cache.fetch ["pnp", "domain", "app_config", key, "value"] do
      result = AppConfig.find_by_key(key)
      result.present? ? result.value : nil
    end
  end

  def flush_cache
    Rails.cache.delete ["pnp", "domain", "app_config", self.key, "value"]
  end

  def to_s
    "#{key} = #{value}"
  end
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
  validates :key,
            uniqueness: true

  validates :key, :value,
            presence: true

  after_commit :flush_cache

  def flush_cache
    Rails.cache.delete ["pnp", "domain", "mapping", self.key, "exists"]
    Rails.cache.delete ["pnp", "domain", "mapping", self.key, "value"]
  end

  def to_s
    "#{key} = #{value}"
  end

  def self.map_entity(entity, key, value)
    Mapping.create!(key: "#{entity}::#{key}", value: value)
  end

  def self.entity_map_exists?(entity, key)
    entity_key = "#{entity}::#{key}"

    Rails.cache.fetch ["pnp", "domain", "mapping", entity_key, "exists"] do
      Mapping.exists?(key: entity_key)
    end
  end

  def self.find_entity_map(entity, key)
    Mapping.find_by_key("#{entity}::#{key}")
  end

  def self.entity_map_value(entity, key)
    entity_key = "#{entity}::#{key}"

    Rails.cache.fetch ["pnp", "domain", "mapping", entity_key, "value"] do
      mapping = find_entity_map(entity, key)
      mapping.present? ? mapping.value : nil
    end
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < RocketPants::Base
  # check for authentication
  before_filter :authenticate

  # check if app is correctly configured
  before_filter :check_app_ready

  def serializer(data, version)
    if data.class == Array
      { each_serializer: array_serializer(data, version) }
    else
      { serializer: object_serializer(data, version) }
    end
  end

  def array_serializer(data, version)
    if data.length > 0
      object_serializer data[0], version
    end
  end

  def object_serializer(data, version)
    case data
      when Subledger::Domain::Balance then balance_serializer(version)
      when Subledger::Domain::Line    then line_serializer(version)
      else puts "Nao era"
    end
  end

  def balance_serializer(version)
    case version.to_i
      when 1 then Api::V1::BalanceSerializer
      else Api::V1::BalanceSerializer
    end
  end

  def line_serializer(version)
    case version.to_i
      when 1 then Api::V1::LineSerializer
      else Api::V1::LineSerializer
    end
  end

protected
  def setup_service
    @setup_service ||= SetupService.new
  end

  def subledger_service
    @subledger_service ||= SubledgerService.new
  end

private
  def check_app_ready
    unless setup_service.setup_ready?
      error! :unknown, metadata: { error_message: "API app is not correctly configured yet" }
    end
  end

  def authenticate
    if Rails.env.production?
      success = authenticate_with_http_basic do |user, password|
        config = Rails.application.config
        config.pnp_user == user and config.pnp_password == password
      end

      unless success
        request_http_basic_authentication
      end
    end
  end
end

app/controllers/api/v1/event_controller.rb
class Api::V1::EventController < Api::ApplicationController
  version 1
  around_action :as_subledger_event

  def read
    # call the service method synchronously
    result = subledger_service.send(@name, @data)

    # get the json serializer
    expose_options = serializer result, params[:version]

    # return the json response
    expose result, expose_options
  end

  def trigger
    # enqueue event for deferred execution
    TriggerWorker.perform_async @name, @data

    # return ok message
    expose :ok
  end

private
  def as_subledger_event
    event_params

    @name = params[:name]
    @data = params[:data].symbolize_keys

    # check if method exists
    unless subledger_service.respond_to? @name
      error! :not_found
    end

    # call the method
    yield
  end

  def event_params
    params.require(:name)
    params.require(:data).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # check for authentication
  before_filter :authenticate

  # check if app is correctly configured
  before_filter :check_app_ready

protected
  def setup_service
    @setup_service ||= SetupService.new
  end

  def subledger_service
    @subledger_service ||= SubledgerService.new
  end

private
  def check_app_ready
    if not (controller_name == "setups" and ["new", "create"].include?(action_name)) and
       not setup_service.setup_ready?

      redirect_to new_setup_path
    end
  end

  def authenticate
    if Rails.env.production?
      success = authenticate_with_http_basic do |user, password|
        config = Rails.application.config
        config.pnp_user == user and config.pnp_password == password
      end

      unless success
        request_http_basic_authentication
      end
    end
  end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  def new
  end

  def create
    setup = params[:setup]

    begin
      setup_service.initial_setup(setup)
      redirect_to action: 'show', notice: "PnP Configured Successfully"

    rescue Exception => e
      logger.error e.backtrace

      flash[:notice] = "Error setting up app: #{e.message}"
      render action: :new
    end
  end

  def show
    @setup = setup_service.get_setup
  end

private
  def setups_params
    params.require(:setup).permit(subledger: [ :email, :identity_desc, :org_desc, :book_desc ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/setup_helper.rb
module SetupHelper
end

app/helpers/simulate_helper.rb
module SimulateHelper
end

app/helpers/subledger_helper.rb
module SubledgerHelper
  def subledger_app_link
   "<a href='https://app.subledger.com' target='_blank'>Open Subledger App</a>".html_safe
  end

private
  def subledger_service
    @subledger_service ||= SubledgerService.new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PlugNPlay - Subledger Integration App</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag "html5shiv", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "respond", "data-turbolinks-track" => true %>
    <![endif]-->

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrap">
      <%= render "/shared/navbar" %>

      <div class="container">
        <%= render "/shared/messages" %>
        <%= yield %>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted credit"><a href="http://subledger.com" target="_blank">Subledger</a> Integration App</p>
      </div>
    </div>
  </body>
</html>

app/views/setups/_subledger.html.erb
<h3>Subledger Config</h3>

<dl class="dl-horizontal">
  <% setup.each do |key, value| %>
    <dt><%= key %></dt>
    <dd><%= value %></dd>
  <% end %>
</dl>

<br/>
<%= subledger_app_link %>

app/views/setups/new.html.erb
<h1>App Initial Setup</h1>

<div class="alert alert-info">
  <strong>Heads Up!:</strong> This page will help with the initial app setup process.
  </br>Please, fill the following fields and click the 'Setup' button.
</div>

<%= form_for :setup, url: setup_path do |f| %>
  <fieldset>
    <legend>Subledger Config</legend>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Ex: email@domain.com.br", autofocus: true, required: true %>
    </div>

    <div class="form-group">
      <%= f.label :identity_desc %>
      <%= f.text_field :identity_desc, class: "form-control", placeholder: "Ex: Test App", required: true%>
    </div>

    <div class="form-group">
      <%= f.label :org_desc %>
      <%= f.text_field :org_desc, class: "form-control", placeholder: "Ex: Test Org", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :book_desc %>
      <%= f.text_field :book_desc, class: "form-control", placeholder: "Ex: Test Book" %>
    </div>
  </fieldset>

  <%= f.submit "Setup", class: "btn btn-default" %>
<% end %>

app/views/setups/show.html.erb
<div class="page-header">
  <h1>Current App Setup: </h1>
</div>

<p>App is configured with following data values:</p>

<%= render "subledger", setup: @setup %>

app/views/shared/_messages.html.erb
<% if alert.present? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Alert</strong> <%= alert %>
  </div>
<% end %>

<% if notice.present? %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Notice: </strong> <%= notice %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Subledger PlugNPlay</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/simulate/simulate_charge_buyer.html.erb
<h1>Simulate Charging a Buyer</h1>

<%= form_for :charge, url: charge_buyer_path do |f| %>
  <div class="form-group">
    <%= f.label :transaction_id %>
    <%= f.text_field :transaction_id, class: "form-control", placeholder: "Ex: 1", autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :purchase_amount %>
    <%= f.text_field :purchase_amount, class: "form-control", placeholder: "Ex: 100", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :payment_fee %>
    <%= f.text_field :payment_fee, class: "form-control", placeholder: "Ex: 10", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :referrer_id %>
    <%= f.text_field :referrer_id, class: "form-control", placeholder: "Ex: referrer1@test.com", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :referrer_amount %>
    <%= f.text_field :referrer_amount, class: "form-control", placeholder: "Ex: 70", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :publisher_id %>
    <%= f.text_field :publisher_id, class: "form-control", placeholder: "Ex: publisher1@test.com", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :publisher_amount %>
    <%= f.text_field :publisher_amount, class: "form-control", placeholder: "Ex: 10", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :distributor_id %>
    <%= f.text_field :distributor_id, class: "form-control", placeholder: "Ex: distributor1@test.com", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :distributor_amount %>
    <%= f.text_field :distributor_amount, class: "form-control", placeholder: "Ex: 10", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", placeholder: "Ex: Purchase (customer@email.com)" %>
  </div>

  <div class="form-group">
    <%= f.label :reference_url %>
    <%= f.url_field :reference_url, class: "form-control", placeholder: "Ex: http://getgranular.com/transaction/100", required: true %>
  </div>
  
  <%= f.submit "Charge", class: "btn btn-default" %>
<% end %>